// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sidebar-redesign/BoldColor.tsx": () => import("../components/mockups/sidebar-redesign/BoldColor.tsx"),
  "./components/mockups/sidebar-redesign/GlassDepth.tsx": () => import("../components/mockups/sidebar-redesign/GlassDepth.tsx"),
  "./components/mockups/sidebar-redesign/SlickDark.tsx": () => import("../components/mockups/sidebar-redesign/SlickDark.tsx")
};
