import { Link } from 'react-router-dom';
import { Zap } from 'lucide-react';

export default function Terms() {
  return (
    <div className="min-h-screen bg-[#0F172A] text-white">
      <nav className="border-b border-[#1E293B] px-6 py-4 flex items-center justify-between max-w-5xl mx-auto">
        <Link to="/" className="flex items-center gap-2">
          <div className="w-8 h-8 gradient-primary rounded-lg flex items-center justify-center">
            <Zap size={16} className="text-white" />
          </div>
          <span className="font-bold text-lg">ReportCraft <span className="text-[#6366F1]">AI</span></span>
        </Link>
        <Link to="/sign-in" className="text-sm text-[#94A3B8] hover:text-white">Sign in</Link>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-extrabold mb-2">Terms of Service</h1>
        <p className="text-sm text-[#64748B] mb-10">Last updated: June 1, 2026</p>

        <div className="space-y-8 text-[#CBD5E1] leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-white mb-3">1. Acceptance of Terms</h2>
            <p>By creating an account or using ReportCraft AI ("the Service"), you agree to these Terms of Service. If you are using the Service on behalf of an organization, you represent that you have authority to bind that organization to these terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">2. Description of Service</h2>
            <p>ReportCraft AI is a SaaS platform that enables marketing agencies to generate AI-powered performance reports by connecting advertising platform data (Google Analytics 4, Google Ads, Meta Ads, LinkedIn Ads) and producing white-labeled PDF reports with narrative analysis.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">3. Free Trial</h2>
            <p>New accounts receive a 14-day free trial with full Agency plan features. No credit card is required to start. At the end of the trial, your account will be read-only until you subscribe to a paid plan. Trial accounts are limited to one trial per person or organization.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">4. Subscription Plans and Billing</h2>
            <p>Paid plans are billed monthly. Payments are processed by Lemon Squeezy. Subscriptions auto-renew unless cancelled. You may cancel at any time; cancellation takes effect at the end of the current billing period. Refunds are handled per our refund policy available at Lemon Squeezy.</p>
            <ul className="list-disc list-inside mt-2 space-y-1.5">
              <li><strong className="text-white">Starter ($79/mo)</strong> — 5 clients, 5 AI reports/month</li>
              <li><strong className="text-white">Agency ($199/mo)</strong> — 15 clients, unlimited AI reports, team members</li>
              <li><strong className="text-white">Agency Pro ($349/mo)</strong> — Unlimited clients, shareable portals, referral program</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">5. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc list-inside mt-2 space-y-1.5">
              <li>Use the Service for illegal purposes or to violate any applicable laws</li>
              <li>Attempt to reverse engineer, decompile, or extract our AI models or proprietary algorithms</li>
              <li>Resell access to the Service without authorization</li>
              <li>Use the Service to generate reports for clients whose data you do not have authorization to access</li>
              <li>Abuse the API rate limits or attempt to circumvent usage limits</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">6. Your Data and OAuth Connections</h2>
            <p>You retain ownership of your data and your clients' data. By connecting advertising platforms, you grant ReportCraft AI permission to read performance metrics for the purpose of generating reports. We do not write to, modify, or manage your advertising campaigns.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">7. AI-Generated Content</h2>
            <p>AI narrative content is generated by large language models (OpenAI GPT-4o / Anthropic Claude). While we design our prompts for accuracy, AI-generated analysis should be reviewed by a qualified professional before being presented to clients as financial or strategic advice. ReportCraft AI is not liable for decisions made based on AI-generated narratives.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">8. Intellectual Property</h2>
            <p>ReportCraft AI and all associated software, branding, and algorithms are our intellectual property. Reports generated through the Service using your data are yours. You may white-label and distribute reports to your clients per your plan's terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">9. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, ReportCraft AI's liability for any claim arising from use of the Service is limited to the amount you paid in the 3 months preceding the claim. We are not liable for indirect, incidental, or consequential damages.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">10. Termination</h2>
            <p>We may suspend or terminate accounts for violations of these terms, abuse, or non-payment. Upon termination, your data will be retained for 30 days and then deleted. You may export your data before termination by contacting support.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">11. Changes to Terms</h2>
            <p>We may update these terms from time to time. We'll notify you via email at least 14 days before material changes take effect. Continued use of the Service after the effective date constitutes acceptance.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">12. Contact</h2>
            <p>For legal inquiries, contact us at <a href="mailto:legal@reportcraft.ai" className="text-[#6366F1] hover:underline">legal@reportcraft.ai</a>.</p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-[#1E293B] flex gap-6 text-sm text-[#64748B]">
          <Link to="/" className="hover:text-white">Home</Link>
          <Link to="/privacy" className="hover:text-white">Privacy Policy</Link>
        </div>
      </div>
    </div>
  );
}
